library(ggplot2)
SEM1<- read.csv("BaseSEM.csv",header=T)

qqplot(SEM1$MERE,SEM1$MEIn, data = SEM1)
qqplot(SEM1$MERE,SEM1$MEIn, data = SEM1)
qqplot(SEM1$MERE,SEM1$MEId, data = SEM1)
qqplot(SEM1$MERE,SEM1$MIAO, data = SEM1)
qqplot(SEM1$MERE,SEM1$MIEE, data = SEM1)
qqplot(SEM1$MERE,SEM1$MIC, data = SEM1)
qqplot(SEM1$MERE,SEM1$SCI, data = SEM1)
qqplot(SEM1$MERE,SEM1$RP, data = SEM1)
qqplot(SEM1$MERE,SEM1$SP, data = SEM1)
qqplot(SEM1$MERE,SEM1$OP, data = SEM1)
qqplot(SEM1$MERE,SEM1$RM, data = SEM1)
qqplot(SEM1$MERE,SEM1$SM, data = SEM1)
qqplot(SEM1$MERE,SEM1$OM, data = SEM1)

par(mfrow=c(4,4))#Não estou conseguindo colocar todos os gráficos na mesma área de plotagem.
a<-qplot(MERE,MEIn, data = SEM1)
(a1<-a+geom_smooth(method="loess",size=1.5))
b<-qplot(MERE,MEId, data = SEM1)
(b1<-b+geom_smooth(method="loess",size=1.5))
c<-qplot(MERE,MIAO, data = SEM1)
(c1<-c+geom_smooth(method="loess",size=1.5))
d<-qplot(MERE,MIEE, data = SEM1)
(d1<-d+geom_smooth(method="loess",size=1.5))
e<-qplot(MERE,MIC, data = SEM1)
(e1<-e+geom_smooth(method="loess",size=1.5))
f<-qplot(MERE,SCI, data = SEM1)
(f1<-f+geom_smooth(method="loess",size=1.5))
g<-qplot(MERE,RP, data = SEM1)
(g1<-g+geom_smooth(method="loess",size=1.5))
h<-qplot(MERE,SP, data = SEM1)
(h1<-h+geom_smooth(method="loess",size=1.5))
i<-qplot(MERE,OP, data = SEM1)
(i1<-h+geom_smooth(method="loess",size=1.5))
j<-qplot(MERE,RM, data = SEM1)
(j1<-h+geom_smooth(method="loess",size=1.5))
k<-qplot(MERE,SM, data = SEM1)
(k1<-h+geom_smooth(method="loess",size=1.5))
l<-qplot(MERE,OM, data = SEM1)
(l1<-h+geom_smooth(method="loess",size=1.5))

library(lattice)
SEM1<- read.csv("BaseSEM.csv",header=T)
pairs(SEM1)
splom(~SEM1)
splom(~SEM1, panel = function(x,y){panel.xyplot(x,y);panel.loess(x,y, col="red")})

